/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package latihangui;

import java.util.ArrayList;
import java.util.List;
import java.util.HashSet; // Tambahkan ini
import java.util.Set;     // Tambahkan ini
import java.util.HashMap; // Tambahkan ini
import java.util.Map;     // Tambahkan ini
import javax.swing.DefaultListModel;

/**
 *
 * @author LENOVO
 */
public class GUIProyek4 extends javax.swing.JFrame {
    
    DefaultListModel<String> dlm;
    List<String> itemsList = new ArrayList<>();       // Ganti nama dari 'items' ke 'itemsList'
    Set<String> itemsSet = new HashSet<>();           // Wadah Set baru
    Map<Integer, String> itemsMap = new HashMap<>(); // Wadah Map baru
    String[] datas = {"buku", "meja", "kursi", "tas", "pintu"};
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIProyek4.class.getName());

    public GUIProyek4() {
        initComponents();
        this.dlm = new DefaultListModel<>();
        this.jListItem.setModel(dlm);
        
        for (String data : datas){
            dlm.addElement(data);
            updateJumDataTersimpan();
        }
    }
    
    private void updateJumDataTersimpan(){
        jLabelSTL.setText("Data tersimpan = " + itemsList.size());
        jLabelSTS.setText("Data tersimpan = " + itemsSet.size());
        jLabelSTM.setText("Data tersimpan = " + itemsMap.size());
    }
    
    private void addItem(String namaItem){
        dlm.addElement(namaItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSTL = new javax.swing.JButton();
        jButtonIDL = new javax.swing.JButton();
        jButtonSTS = new javax.swing.JButton();
        jButtonIDS = new javax.swing.JButton();
        jButtonSTM = new javax.swing.JButton();
        jButtonIDM = new javax.swing.JButton();
        jLabelSTM = new javax.swing.JLabel();
        jLabelSTS = new javax.swing.JLabel();
        jLabelSTL = new javax.swing.JLabel();
        jLabelItemName = new javax.swing.JLabel();
        jTextFieldItem = new javax.swing.JTextField();
        jButtonClearAll = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSTL.setText("Save to List ->");
        jButtonSTL.addActionListener(this::jButtonSTLActionPerformed);

        jButtonIDL.setText("<- Insert Data List");
        jButtonIDL.addActionListener(this::jButtonIDLActionPerformed);

        jButtonSTS.setText("Save to Set ->");
        jButtonSTS.addActionListener(this::jButtonSTSActionPerformed);

        jButtonIDS.setText("<- Insert Data Set");
        jButtonIDS.addActionListener(this::jButtonIDSActionPerformed);

        jButtonSTM.setText("Save to Map ->");
        jButtonSTM.addActionListener(this::jButtonSTMActionPerformed);

        jButtonIDM.setText("<- Insert data Map");
        jButtonIDM.addActionListener(this::jButtonIDMActionPerformed);

        jLabelSTM.setText("Data Tersimpan = 0");

        jLabelSTS.setText("Data Tersimpan = 0");

        jLabelSTL.setText("Data Tersimpan = 0");

        jLabelItemName.setText("Item Name:");

        jButtonClearAll.setText("Clear All");
        jButtonClearAll.addActionListener(this::jButtonClearAllActionPerformed);

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(this::jButtonUpdateActionPerformed);

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jListItem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonClearAll)
                        .addGap(147, 147, 147)
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelItemName)
                            .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonSTL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonIDL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSTS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonIDS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSTM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonIDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSTS)
                                    .addComponent(jLabelSTL)
                                    .addComponent(jLabelSTM))))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSTL)
                            .addComponent(jLabelSTL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIDL)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSTS)
                            .addComponent(jLabelSTS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonIDS)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSTM)
                            .addComponent(jLabelSTM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonIDM)
                        .addGap(24, 24, 24)
                        .addComponent(jLabelItemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClearAll)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonDelete))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIDSActionPerformed
        dlm.clear();
        for (String item : itemsSet){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jButtonIDSActionPerformed

    private void jButtonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearAllActionPerformed
        dlm.clear();
    }//GEN-LAST:event_jButtonClearAllActionPerformed

    private void jButtonSTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSTLActionPerformed
        itemsList.clear();
        for (int i = 0; i < dlm.getSize(); i++){
            itemsList.add(dlm.getElementAt(i));
        }
        updateJumDataTersimpan();
    }//GEN-LAST:event_jButtonSTLActionPerformed

    private void jButtonIDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIDLActionPerformed
        dlm.clear(); // Bersihkan jList dulu biar ga double data
        for (String item : itemsList){
            dlm.addElement(item);
        }
    }//GEN-LAST:event_jButtonIDLActionPerformed

    private void jButtonSTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSTSActionPerformed
        itemsSet.clear();
        for (int i = 0; i < dlm.getSize(); i++){
            itemsSet.add(dlm.getElementAt(i)); 
        }
        updateJumDataTersimpan();
    }//GEN-LAST:event_jButtonSTSActionPerformed

    private void jButtonSTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSTMActionPerformed
        itemsMap.clear();
        for (int i = 0; i < dlm.getSize(); i++){
            itemsMap.put(i, dlm.getElementAt(i)); // i sebagai key, nama item sebagai value
        }
        updateJumDataTersimpan();
    }//GEN-LAST:event_jButtonSTMActionPerformed

    private void jButtonIDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIDMActionPerformed
        dlm.clear();
        for (int i = 0; i < itemsMap.size(); i++){
            dlm.addElement(itemsMap.get(i)); // Mengambil data berdasarkan Key (angka i)
        }
    }//GEN-LAST:event_jButtonIDMActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        addItem(jTextFieldItem.getText());
        jTextFieldItem.setText("");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        int index = jListItem.getSelectedIndex();
        if (index != -1) { // Proteksi
            String selected = jTextFieldItem.getText();
            dlm.setElementAt(selected, index);
            jTextFieldItem.setText("");
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int index = jListItem.getSelectedIndex();
        if (index != -1) { // Proteksi
            dlm.removeElementAt(index);
            jTextFieldItem.setText("");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIProyek4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClearAll;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonIDL;
    private javax.swing.JButton jButtonIDM;
    private javax.swing.JButton jButtonIDS;
    private javax.swing.JButton jButtonSTL;
    private javax.swing.JButton jButtonSTM;
    private javax.swing.JButton jButtonSTS;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelItemName;
    private javax.swing.JLabel jLabelSTL;
    private javax.swing.JLabel jLabelSTM;
    private javax.swing.JLabel jLabelSTS;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldItem;
    // End of variables declaration//GEN-END:variables
}
