
package jdbc.program;


import javax.swing.DefaultListModel;
import jdbc.model.Mahasiswa;            // Sesuaikan dengan nama package model kamu
import jdbc.service.MysqlMahasiswaService;


/**
 *
 * @author LENOVO
 */
public class JFrameMain extends javax.swing.JFrame {
    private MysqlMahasiswaService service;
    private DefaultListModel<String> dlmId;
    private DefaultListModel<String> dlmNama;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameMain.class.getName());

    public JFrameMain() {
        initComponents();
        service = new MysqlMahasiswaService();
        
        // Inisialisasi model
        dlmId = new DefaultListModel<>();
        dlmNama = new DefaultListModel<>();
        
        // Hubungkan model ke masing-masing JList kamu
        jListID.setModel(dlmId);
        jListNama.setModel(dlmNama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanel1 = new javax.swing.JScrollPane();
        jListID = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListNama = new javax.swing.JList<>();
        jLabelID = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabelJudul = new javax.swing.JLabel();
        jButtonAmbil = new javax.swing.JButton();
        jLabelInpNama = new javax.swing.JLabel();
        jTextFieldInpNama = new javax.swing.JTextField();
        jButtonTambah = new javax.swing.JButton();
        jTextFieldEditID = new javax.swing.JTextField();
        jTextFieldEditNama = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        jTextFieldHapusID = new javax.swing.JTextField();
        jTextFieldHapusNama = new javax.swing.JTextField();
        jButtonHapus = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListID.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPanel1.setViewportView(jListID);

        jListNama.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListNama);

        jLabelID.setText("ID");

        jLabelNama.setText("NAMA");

        jLabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelJudul.setText("Kelola Data Mahasiswa");

        jButtonAmbil.setText("Ambil Semua Data");
        jButtonAmbil.addActionListener(this::jButtonAmbilActionPerformed);

        jLabelInpNama.setText("Nama:");

        jButtonTambah.setText("Tambahkan");
        jButtonTambah.addActionListener(this::jButtonTambahActionPerformed);

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(this::jButtonHapusActionPerformed);

        jButtonReset.setText("Reset Indeks");
        jButtonReset.addActionListener(this::jButtonResetActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNama)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJudul)
                            .addComponent(jButtonAmbil)
                            .addComponent(jLabelInpNama)
                            .addComponent(jTextFieldInpNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTambah)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldHapusID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jTextFieldEditID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonEdit)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldHapusNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonHapus)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonReset)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelID)
                            .addComponent(jLabelNama))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPanel1)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelJudul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAmbil)
                        .addGap(26, 26, 26)
                        .addComponent(jLabelInpNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldInpNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTambah)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEditID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEditNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldHapusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHapusNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jButtonReset)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAmbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmbilActionPerformed
        dlmId.clear();
        dlmNama.clear();
        java.util.List<Mahasiswa> listMhs = service.getAll();
        for (Mahasiswa mhs : listMhs) {
            dlmId.addElement(String.valueOf(mhs.getId())); 
            dlmNama.addElement(mhs.getNama());            
        }
    }//GEN-LAST:event_jButtonAmbilActionPerformed

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        String namaBaru = jTextFieldInpNama.getText().trim();

        if (!namaBaru.isEmpty()) {
            // Kirim ID 0 saja, biarkan MySQL AUTO_INCREMENT yang menentukan angkanya
            Mahasiswa mhs = new Mahasiswa(0, namaBaru);

            service.add(mhs); 
            jTextFieldInpNama.setText("");

            // Refresh tampilan list
            jButtonAmbilActionPerformed(evt);
        }
    }//GEN-LAST:event_jButtonTambahActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        int index = jListID.getSelectedIndex(); // Menggunakan jListID huruf besar

        if (index != -1) { 
            int idSelected = Integer.parseInt(dlmId.getElementAt(index));
            String namaBaru = jTextFieldEditNama.getText().trim(); // Menggunakan jTextFieldEditNama

            if (!namaBaru.isEmpty()) {
                Mahasiswa mhs = new Mahasiswa();
                mhs.setId(idSelected);
                mhs.setNama(namaBaru);

                service.update(mhs);
                jTextFieldEditID.setText("");
                jTextFieldEditNama.setText("");

                jButtonAmbilActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        int index = jListID.getSelectedIndex(); // Menggunakan jListID huruf besar

        if (index != -1) { 
            int idSelected = Integer.parseInt(dlmId.getElementAt(index));

            service.delete(idSelected);
            jTextFieldHapusID.setText("");
            jTextFieldHapusNama.setText("");

            jButtonAmbilActionPerformed(evt);
        }
    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // 1. Eksekusi reset auto-increment ke database MySQL
        service.indexReset();
        
        // 2. Batalkan seleksi baris pada JList agar tidak ada data yang tersorot
        jListID.clearSelection();
        jListNama.clearSelection();
        
        // 3. CARA YANG BENAR: Picu tombol ambil data untuk merefresh tampilan secara aman
        jButtonAmbil.doClick();
    }//GEN-LAST:event_jButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAmbil;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelInpNama;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JList<String> jListID;
    private javax.swing.JList<String> jListNama;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPanel1;
    private javax.swing.JTextField jTextFieldEditID;
    private javax.swing.JTextField jTextFieldEditNama;
    private javax.swing.JTextField jTextFieldHapusID;
    private javax.swing.JTextField jTextFieldHapusNama;
    private javax.swing.JTextField jTextFieldInpNama;
    // End of variables declaration//GEN-END:variables
}
